spring.jackson.serialization.INDENT_OUTPUT: true

logging.level:
  "org.springframework": ERROR
  "org.elasticsearch": ERROR
  "org.hibernate": ERROR
  "io.undertow": ERROR
  "org.xnio": ERROR
  "org.apache": ERROR

server:
  port: 8080
  address: 127.0.0.1
  sessionTimeout: 0

management.port: -1

spring:
  main:
    show-banner: false
  datasource:
    platform: h2
    url: "jdbc:h2:mem:dev;DB_CLOSE_ON_EXIT=FALSE"
  mustache:
    cache: false
    suffix: .mustache

spring.jpa.hibernate.ddl-auto: create-drop

spring.data.rest.base-path: /_/rest/
